baseURL: "https://example.com"
languageCode: "en-us"
title: "HealthBlog - Your Wellness Guide"
theme: "blog-theme"

# Site Configuration
params:
  # Site description
  description: "Your trusted source for evidence-based health, nutrition, and wellness information. Discover natural solutions, healthy recipes, and expert advice for optimal living."
  
  # Author information
  author: "Dr. Sarah Wilson"
  
  # Logo and branding
  logo: "/images/logo.png"
  favicon: "/images/favicon.ico"
  
  # Social media links
  social:
    facebook: "https://facebook.com/healthblog"
    twitter: "https://twitter.com/healthblog"
    instagram: "https://instagram.com/healthblog"
    youtube: "https://youtube.com/healthblog"
    pinterest: "https://pinterest.com/healthblog"
  
  # Newsletter signup
  newsletter:
    enabled: true
    provider: "mailchimp" # or "convertkit", "mailerlite"
    endpoint: "https://your-mailchimp-endpoint.com"
  
  # Google Analytics
  googleAnalytics: "G-XXXXXXXXXX"
  
  # Comments
  comments:
    enabled: true
    provider: "disqus" # or "utterances"
    disqus_shortname: "your-disqus-shortname"

# Menu configuration
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Health"
      url: "/health/"
      weight: 2
    - name: "Nutrition"
      url: "/nutrition/"
      weight: 3
    - name: "Recipes"
      url: "/recipes/"
      weight: 4
    - name: "Fitness"
      url: "/fitness/"
      weight: 5
    - name: "Beauty"
      url: "/beauty/"
      weight: 6
    - name: "About"
      url: "/about/"
      weight: 7
    - name: "Contact"
      url: "/contact/"
      weight: 8

# Pagination
paginate: 6
paginatePath: "page"

# Markup configuration
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "github"
    lineNos: true

# Taxonomies
taxonomies:
  category: "categories"
  tag: "tags"
  author: "authors"

# Related content
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: "keywords"
      weight: 100
    - name: "tags"
      weight: 80
    - name: "categories"
      weight: 60

# Output formats
outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML"]
  section: ["HTML", "RSS"]

# Security
security:
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']